# Generated by Django 5.2.15 on 2026-06-10 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_installation_id', models.IntegerField(help_text='Unique installation id supplied by GitHub during app setup.', unique=True)),
                ('encrypted_gemini_key', models.BinaryField(blank=True, null=True)),
                ('encrypted_e2b_key', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(help_text='Full name, e.g. "owner/repository-name".', max_length=255)),
                ('ignored_directories', models.JSONField(blank=True, default=list, help_text='Directory globs skipped during AST parsing, e.g. ["tests/*"].')),
                ('max_concurrency', models.IntegerField(default=2, help_text='Maximum overlapping active review executions for this repo.')),
                ('org_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='tenancy.organizationconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('commit_sha', models.CharField(help_text='Latest commit reviewed; actions only run on the latest SHA.', max_length=64)),
                ('langgraph_thread_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Pointer key Celery workers use to recall checkpoint state.')),
                ('current_status', models.CharField(choices=[('ANALYZING', 'Analyzing'), ('AWAITING_HUMAN', 'Awaiting human'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed')], default='ANALYZING', max_length=20)),
                ('active_jobs', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenancy.reposettings')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reposettings',
            constraint=models.UniqueConstraint(fields=('org_config', 'repository_name'), name='unique_repo_per_org'),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['repo_settings', 'pr_number'], name='tenancy_rev_repo_se_94d296_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['current_status'], name='tenancy_rev_current_34ec38_idx'),
        ),
    ]
