# Generated by Django 5.2.15 on 2026-06-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationconfig',
            name='encrypted_gemini_key',
        ),
        migrations.AddField(
            model_name='organizationconfig',
            name='encrypted_llm_key',
            field=models.BinaryField(blank=True, help_text='AES-encrypted API key string matching the selected provider.', null=True),
        ),
        migrations.AddField(
            model_name='organizationconfig',
            name='llm_base_url',
            field=models.URLField(blank=True, help_text='Custom endpoint wrapper URL (Required for Local Ollama, e.g., http://localhost:11434/v1)', null=True),
        ),
        migrations.AddField(
            model_name='organizationconfig',
            name='llm_model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='Target model execution string (e.g., llama3-70b-8192, gpt-4o, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationconfig',
            name='llm_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('groq', 'Groq'), ('local', 'Local Setup / Ollama')], default='gemini', help_text='Active LLM provider for processing reviews.', max_length=20),
        ),
    ]
