# Generated by Django 5.2.15 on 2026-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_remove_organizationconfig_encrypted_gemini_key_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reviewsession',
            name='tenancy_rev_repo_se_94d296_idx',
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='file_path',
            field=models.CharField(default='', help_text='The specific file this review session is targeting.', max_length=500),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['repo_settings', 'pr_number', 'file_path'], name='tenancy_rev_repo_se_21e08a_idx'),
        ),
    ]
